Repository Jropp/jason-ropp-js-iobp, pull requests merged in 2018-08, with the labels that each got.

#64 Onboarding Project: Card Expand and Collapse
  .vs/slnx.sqlite
  README.md
  src/index.ejs
  src/user-component/user-component.html
  src/user-list/user-list.html
Labels: in progress, needs review, styling

#69 Popup messages
  src/api/user-database.js
  src/user-component/user-component.html
  src/user-list/user-list.html
Labels: do not merge, needs review

#73 Editing Hover effects, style of (no-users) message, and autofill background
  src/user-component/user-component.html
  src/user-list/user-list.html
Labels: needs review, styling

#75 Onboarding Project: Bug Fix - Card styles reset immediately to default after delete
  src/user-component/user-component.html
Labels: needs review

#76 Onboarding Project: Add Icons To User Form
  src/design/svgs/jha-add-person-icon.html
  src/design/svgs/jha-cancel-icon.html
  src/design/svgs/jha-department-icon.html
  src/design/svgs/jha-drop-arrow-icon.html
  src/design/svgs/jha-email-icon.html
  src/design/svgs/jha-person-icon.html
  src/design/svgs/jha-phone-icon.html
  src/design/svgs/jha-up-arrow-icon.html
  src/user-component/user-component.html
Labels: needs review

#80 Fixes unresolved conflict in master
  src/user-component/user-component.html
Labels: Refactor, needs review

#79 Stylesheet
  package.json
  src/index.js
  src/user-component/user-component.css
  src/user-component/user-component.html
  src/user-list/user-list.html
  webpack.config.js
Labels: needs review

#82 Onboarding Project: Bug Fix – Persistent Collapse User Detail Arrow Icon
  src/user-component/user-component.html
Labels: bug, needs review

#84 Onboarding Project: Bug Fix – Expanding User Card Requires 2 Clicks After A Delete
  src/user-component/user-component.html
Labels: Refactor, bug

#86 Onboarding Project: User Card Spacing Fix.
  src/user-component/user-component.html
Labels: needs review, styling

#88 Onboard Project: JHA-Design-Components-Setup
  build-tools/jha-design-components-loader.js
  package.json
  src/user-list/user-list.html
  webpack.config.js
Labels: do not merge, in progress, needs review

#90 Bug-Fix: User Name Header Shouldn't Change Till Save
  src/user-component/user-component.html
Labels: bug, needs review

#94 Onboard Project: Bug-Fix Warning messages
  src/user-component/user-component.css
  src/user-component/user-component.html
  src/user-list/user-list.html
Labels: bug, needs review, styling

#97 Onboarding Project: Format Card to Match JHA Design
  README.md
  src/user-component/user-component.css
  src/user-component/user-component.html
Labels: needs review

#98 Onboarding Project: Added CREATE_MODE
  README.md
  src/user-component/user-component.html
  src/user-list/user-list.html
Labels: needs review

#81 Onboarding Project: User-List Cleanup
  src/user-list/user-list.html
Labels: Refactor, needs review

#102 Onboarding Project: Utils Refactor
  src/api/utils.js
  src/user-component/user-component.html
Labels: needs review

#103 Onboarding Project: Database refactor
  src/api/user-database.js
  src/user-component/user-component.html
  src/user-list/user-list.html
Labels: Refactor, needs review
